-- Archivo para limpiar la base de datos

IF OBJECT_ID('GROUPBY4.Involucrados_Incidente', 'U') IS NOT NULL DROP TABLE GROUPBY4.Involucrados_Incidente;
IF OBJECT_ID('GROUPBY4.Incidente', 'U') IS NOT NULL DROP TABLE GROUPBY4.Incidente;
IF OBJECT_ID('GROUPBY4.Cambio_Neumatico', 'U') IS NOT NULL DROP TABLE GROUPBY4.Cambio_Neumatico;
IF OBJECT_ID('GROUPBY4.Parada', 'U') IS NOT NULL DROP TABLE GROUPBY4.Parada;
IF OBJECT_ID('GROUPBY4.Motor_Tele', 'U') IS NOT NULL DROP TABLE GROUPBY4.Motor_Tele;
IF OBJECT_ID('GROUPBY4.Freno_Tele', 'U') IS NOT NULL DROP TABLE GROUPBY4.Freno_Tele;
IF OBJECT_ID('GROUPBY4.Neumatico_Tele', 'U') IS NOT NULL DROP TABLE GROUPBY4.Neumatico_Tele;
IF OBJECT_ID('GROUPBY4.Caja_Tele', 'U') IS NOT NULL DROP TABLE GROUPBY4.Caja_Tele;
IF OBJECT_ID('GROUPBY4.Telemetria', 'U') IS NOT NULL DROP TABLE GROUPBY4.Telemetria;
IF OBJECT_ID('GROUPBY4.Sector', 'U') IS NOT NULL DROP TABLE GROUPBY4.Sector;
IF OBJECT_ID('GROUPBY4.Carrera', 'U') IS NOT NULL DROP TABLE GROUPBY4.Carrera;
IF OBJECT_ID('GROUPBY4.Sector_Tipo', 'U') IS NOT NULL DROP TABLE GROUPBY4.Sector_Tipo;
IF OBJECT_ID('GROUPBY4.Caja', 'U') IS NOT NULL DROP TABLE GROUPBY4.Caja;
IF OBJECT_ID('GROUPBY4.Motor', 'U') IS NOT NULL DROP TABLE GROUPBY4.Motor;
IF OBJECT_ID('GROUPBY4.Neumatico', 'U') IS NOT NULL DROP TABLE GROUPBY4.Neumatico;
IF OBJECT_ID('GROUPBY4.Neumatico_Tipo', 'U') IS NOT NULL DROP TABLE GROUPBY4.Neumatico_Tipo;
IF OBJECT_ID('GROUPBY4.Freno', 'U') IS NOT NULL DROP TABLE GROUPBY4.Freno;
IF OBJECT_ID('GROUPBY4.Auto', 'U') IS NOT NULL DROP TABLE GROUPBY4.Auto;
IF OBJECT_ID('GROUPBY4.Incidente_Tipo', 'U') IS NOT NULL DROP TABLE GROUPBY4.Incidente_Tipo;
IF OBJECT_ID('GROUPBY4.Bandera', 'U') IS NOT NULL DROP TABLE GROUPBY4.Bandera;
IF OBJECT_ID('GROUPBY4.Bandera_Tipo', 'U') IS NOT NULL DROP TABLE GROUPBY4.Bandera_Tipo;
IF OBJECT_ID('GROUPBY4.Piloto', 'U') IS NOT NULL DROP TABLE GROUPBY4.Piloto;
IF OBJECT_ID('GROUPBY4.Escuderia', 'U') IS NOT NULL DROP TABLE GROUPBY4.Escuderia;
IF OBJECT_ID('GROUPBY4.Nacionalidad', 'U') IS NOT NULL DROP TABLE GROUPBY4.Nacionalidad;
IF OBJECT_ID('GROUPBY4.Circuito', 'U') IS NOT NULL DROP TABLE GROUPBY4.Circuito;
IF OBJECT_ID('GROUPBY4.Pais', 'U') IS NOT NULL DROP TABLE GROUPBY4.Pais;

IF OBJECT_ID('GROUPBY4.escuderia_obtener', 'U') IS NOT NULL DROP TABLE GROUPBY4.escuderia_obtener; 
IF OBJECT_ID('GROUPBY4.piloto_nombre_apellido', 'U') IS NOT NULL DROP TABLE GROUPBY4.piloto_nombre_apellido; 
IF OBJECT_ID('GROUPBY4.obtener_id_neum', 'U') IS NOT NULL DROP TABLE GROUPBY4.obtener_id_neum; 
IF OBJECT_ID('GROUPBY4.piloto_obtener_auto', 'U') IS NOT NULL DROP TABLE GROUPBY4.piloto_obtener_auto; 

