IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'GROUPBY4')
BEGIN
	EXEC ('CREATE SCHEMA GROUPBY4')
END
GO

IF OBJECT_ID('GROUPBY4.Nacionalidad', 'U') IS NOT NULL DROP TABLE GROUPBY4.Nacionalidad;
IF OBJECT_ID('GROUPBY4.Piloto', 'U') IS NOT NULL DROP TABLE GROUPBY4.Piloto;
IF OBJECT_ID('GROUPBY4.Escuderia', 'U') IS NOT NULL DROP TABLE GROUPBY4.Escuderia;

CREATE TABLE GROUPBY4.Nacionalidad
(
	naci_codigo INT IDENTITY PRIMARY KEY,
	naci_nombre NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE GROUPBY4.Piloto
(
	pilo_codigo INT IDENTITY PRIMARY KEY,
	pilo_nombre NVARCHAR(255) NOT NULL,
	pilo_apellido NVARCHAR(255) NOT NULL,
	pilo_nacionalidad INT NOT NULL, -- fk
	pilo_fecha_nacimiento DATE NOT NULL
)
GO

CREATE TABLE GROUPBY4.Escuderia
(
	escu_codigo INT IDENTITY PRIMARY KEY,
	escu_nombre NVARCHAR(255) NOT NULL,
	escu_nacionalidad INT NOT NULL --fk
)
GO

CREATE TABLE GROUPBY4.Auto
(
	auto_codigo INT IDENTITY PRIMARY KEY,
	auto_modelo NVARCHAR(255) NOT NULL,
	auto_numero INT NOT NULL,
	auto_piloto INT NOT NULL, --fk
	auto_escuderia INT NOT NULL --fk
)
GO

CREATE TABLE GROUPBY4.Bandera
(
	band_codigo INT IDENTITY PRIMARY KEY,
	band_detalle NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE GROUPBY4.Incidente_Tipo
(
	inci_tipo_codigo INT IDENTITY PRIMARY KEY,
	inci_tipo_detalle NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE GROUPBY4.Pais
(
	pais_codigo INT IDENTITY PRIMARY KEY,
	pais_nombre NVARCHAR(255) NOT NULL
)
GO
--CODIGO CIRCUITO NO DEBERIA SER UN IDENTITY PORQUE EN LA TABLA MAESTRA YA HAY UN CODIGO CIRCUITO
CREATE TABLE GROUPBY4.Circuito 
(
	circ_codigo INT IDENTITY PRIMARY KEY,
	circ_nombre NVARCHAR(255) NOT NULL,
	circ_pais INT NOT NULL --(fk)
)
GO

--CODIGO CARRERA NO DEBERIA SER UN IDENTITY PORQUE EN LA TABLA MAESTRA YA HAY UN CODIGO CARRERA
CREATE TABLE GROUPBY4.Carrera 
(
	carr_codigo INT PRIMARY KEY,
	carr_fecha DATE NOT NULL ,
	carr_clima NVARCHAR(100) NOT NULL,
	carr_total_carrera DECIMAL(18, 2) NOT NULL,
	carr_cant_vueltas INT NOT NULL,
	carr_circuito INT NOT NULL -- (fk)
)
GO

CREATE TABLE GROUPBY4.Sector_Tipo
(
	sect_tipo_codigo INT IDENTITY PRIMARY KEY,
	sect_tipo_nombre NVARCHAR(255) NOT NULL
)
GO
--SECTOR CODIGO NO DEBERIA SER UN IDENTITY PORQUE YA EXISTE EL CODIGO SECTOR
CREATE TABLE GROUPBY4.Sector
(
	sect_codigo INT PRIMARY KEY,
	sect_distancia DECIMAL(18, 2) NOT NULL,
	sect_tipo INT NOT NULL, -- (fk)
	sect_circuito INT NOT NULL -- (fk) 
)
GO

CREATE TABLE GROUPBY4.Incidente
(
	inci_codigo INT IDENTITY PRIMARY KEY,
	inci_bandera INT NOT NULL,-- fk
	inci_carrera INT NOT NULL, --fk
	inci_tipo INT NOT NULL, --fk
	inci_sector INT  NOT NULL, --fk
	inci_tiempo  DECIMAL(18, 2) NOT NULL
)
GO

INSERT INTO GROUPBY4.Nacionalidad
SELECT PILOTO_NACIONALIDAD FROM gd_esquema.Maestra
union
SELECT UPPER(ESCUDERIA_NACIONALIDAD) FROM gd_esquema.Maestra

INSERT INTO GROUPBY4.Piloto
SELECT DISTINCT PILOTO_NOMBRE, PILOTO_APELLIDO, n.naci_codigo, PILOTO_FECHA_NACIMIENTO FROM gd_esquema.Maestra m
INNER JOIN GROUPBY4.Nacionalidad n ON m.PILOTO_NACIONALIDAD = n.naci_nombre

INSERT INTO GROUPBY4.Escuderia
SELECT DISTINCT ESCUDERIA_NOMBRE, n.naci_codigo FROM gd_esquema.Maestra m
INNER JOIN GROUPBY4.Nacionalidad n ON UPPER(m.ESCUDERIA_NACIONALIDAD) = n.naci_nombre 

INSERT INTO GROUPBY4.Auto
SELECT DISTINCT AUTO_MODELO, AUTO_NUMERO, p.pilo_codigo, e.escu_codigo FROM gd_esquema.Maestra m
INNER JOIN GROUPBY4.Escuderia e
ON e.escu_nombre = m.ESCUDERIA_NOMBRE
INNER JOIN GROUPBY4.Piloto p
ON p.pilo_nombre+p.pilo_apellido = m.PILOTO_NOMBRE+m.PILOTO_APELLIDO
ORDER BY e.escu_codigo, AUTO_NUMERO

INSERT INTO GROUPBY4.Bandera
SELECT DISTINCT INCIDENTE_BANDERA FROM gd_esquema.Maestra
WHERE INCIDENTE_BANDERA IS NOT NULL

INSERT INTO GROUPBY4.Incidente_Tipo
SELECT DISTINCT INCIDENTE_TIPO FROM gd_esquema.Maestra
WHERE INCIDENTE_TIPO IS NOT NULL

INSERT INTO GROUPBY4.Pais
SELECT DISTINCT CIRCUITO_PAIS FROM gd_esquema.Maestra

INSERT INTO GROUPBY4.Circuito
SELECT DISTINCT CIRCUITO_NOMBRE, pais_codigo FROM gd_esquema.Maestra m
INNER JOIN GROUPBY4.Pais p
ON m.CIRCUITO_PAIS = p.pais_nombre
ORDER BY 1 ASC

INSERT INTO GROUPBY4.Carrera
SELECT 
DISTINCT CODIGO_CARRERA, CARRERA_FECHA, CARRERA_CLIMA, CARRERA_TOTAL_CARRERA, CARRERA_CANT_VUELTAS, c.circ_codigo
FROM gd_esquema.Maestra m
INNER JOIN GROUPBY4.Circuito c
ON c.circ_nombre = m.CIRCUITO_NOMBRE
ORDER BY 1

INSERT INTO GROUPBY4.Sector_Tipo
SELECT DISTINCT SECTO_TIPO FROM gd_esquema.Maestra

INSERT INTO GROUPBY4.Sector
SELECT DISTINCT CODIGO_SECTOR, SECTOR_DISTANCIA, st.sect_tipo_codigo,  c.circ_codigo FROM gd_esquema.Maestra m
INNER JOIN GROUPBY4.Sector_Tipo st
ON st.sect_tipo_nombre = m.SECTO_TIPO
INNER JOIN GROUPBY4.Circuito c
ON c.circ_nombre = m.CIRCUITO_NOMBRE
ORDER BY 1

INSERT INTO GROUPBY4.Incidente
SELECT 
	b.band_codigo, 
	CODIGO_CARRERA, 
	i.inci_tipo_codigo, 
	CODIGO_SECTOR,
	INCIDENTE_TIEMPO
FROM gd_esquema.Maestra m
INNER JOIN GROUPBY4.Bandera b 
ON m.INCIDENTE_BANDERA = b.band_detalle
INNER JOIN GROUPBY4.Incidente_Tipo i
ON m.INCIDENTE_TIPO = i.inci_tipo_detalle
WHERE INCIDENTE_TIEMPO is not null
ORDER BY CODIGO_CARRERA


